version: '3'
services:
  client:
    build: ./client
    ports:
      - "3000:3000"  
    depends_on:
      - mongodb-backend
      - hcu_server

  mongodb-backend:
    build: ./mongodb-backend
    ports:
      - "4000:4000"  
    depends_on:
      - mongodb

  hcu_server:
    build: ./hcu_server
    ports:
      - "5000:5000" 

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

networks:
  default:
    driver: bridge

volumes:
  mongo-data:
