version: '3'
services:
  client:
    image: magarthai/demo-client:latest  # เปลี่ยนชื่อภาพเป็นชื่อที่ถูกต้องของ client
    ports:
      - "3000:3000"
    depends_on:
      - mongodb-backend
      - hcu_server

  mongodb-backend:
    image: magarthai/demo-mongodb-backend:latest  # เปลี่ยนชื่อภาพเป็นชื่อที่ถูกต้องของ mongodb-backend
    ports:
      - "4000:4000"
    depends_on:
      - mongodb

  hcu_server:
    image: magarthai/demo-hcu-server:latest  # เปลี่ยนชื่อภาพเป็นชื่อที่ถูกต้องของ hcu_server
    ports:
      - "5000:5000"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

networks:
  default:
    driver: bridge

volumes:
  mongo-data:
