version: '3'
services:
  client:
    image: magarthai/client:latest
    ports:
      - "3000:3000"
    depends_on:
      - mongodb-backend
      - hcu_server

  mongodb-backend:
    image: magarthai/mongodb-backend:latest
    ports:
      - "4000:4000"
    depends_on:
      - mongodb

  hcu_server:
    image: magarthai/hcu_server:latest
    ports:
      - "5000:5000"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

networks:
  default:
    driver: bridge

volumes:
  mongo-data:
