name: deployment dev

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push client
        uses: docker/build-push-action@v4
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/client:${{ github.run_number }}, ${{ secrets.DOCKERHUB_USERNAME }}/client:latest

      - name: Build and push hcu_server
        uses: docker/build-push-action@v4
        with:
          context: ./hcu_server
          file: ./hcu_server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hcu_server:${{ github.run_number }}, ${{ secrets.DOCKERHUB_USERNAME }}/hcu_server:latest

      - name: Build and push mongodb-backend
        uses: docker/build-push-action@v4
        with:
          context: ./mongodb-backend
          file: ./mongodb-backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mongodb-backend:${{ github.run_number }}, ${{ secrets.DOCKERHUB_USERNAME }}/mongodb-backend:latest

  pull:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull images from Docker Hub
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/client:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/hcu_server:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mongodb-backend:latest

  deploy:
    needs: pull
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Docker compose up
        run: docker-compose -f docker-compose.yml up -d
